### ISSUE TITLE
default helm install fails with a 3 worker node config

### ISSUE THREAD

**Issue by LordNoteworthy** [couchbase-partners/helm-charts#121]
Hello,

I created a kind cluster with the following config (fresh K8s v1.27.3):
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
- role: worker
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
- role: worker
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
- role: worker
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
```

Helm version:
```
❯ helm version
version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.5"}
```

I installed the helm chart with default cfg: 

```sh
helm install couchbase-cluster --set cluster.name=couchbase-cluster couchbase/couchbase-operator
```
Status of the pods:
```
❯ kubectl get pods
NAME                                                      READY   STATUS             RESTARTS          AGE
couchbase-cluster-0000                                    1/1     Running            0                 30m
couchbase-cluster-0001                                    1/1     Running            0                 30m
couchbase-cluster-0002                                    1/1     Running            0                 30m
```
The operator log shows that there is a reconciliation issue: 
```console
{"level":"info","ts":"2024-02-02T21:35:55Z","logger":"cluster","msg":"Reconciliation failed","cluster":"default/couchbase","error":"dial tcp 172.20.0.2:30582: connect: connection refused","stack":"github.com/couchbase/couchbase-operator/pkg/util/netutil.WaitForHostPort\n\tgithub.com/couchbase/couchbase-operator/pkg/util/netutil/netutil.go:37\ngithub.com/couchbase/couchbase-operator/pkg/cluster.waitAlternateAddressReachable\n\tgithub.com/couchbase/couchbase-operator/pkg/cluster/networking.go:76\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).reconcileMemberAlternateAddresses\n\tgithub.com/couchbase/couchbase-operator/pkg/cluster/networking.go:228\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*ReconcileMachine).handleNodeServices\n\tgithub.com/couchbase/couchbase-operator/pkg/cluster/nodereconcile.go:1268\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*ReconcileMachine).exec\n\tgithub.com/couchbase/couchbase-operator/pkg/cluster/nodereconcile.go:309\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).reconcileMembers\n\tgithub.com/couchbase/couchbase-operator/pkg/cluster/reconcile.go:267\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).reconcile\n\tgithub.com/couchbase/couchbase-operator/pkg/cluster/reconcile.go:177\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).runReconcile\n\tgithub.com/couchbase/couchbase-operator/pkg/cluster/cluster.go:492\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).Update\n\tgithub.com/couchbase/couchbase-operator/pkg/cluster/cluster.go:535\ngithub.com/couchbase/couchbase-operator/pkg/controller.(*CouchbaseClusterReconciler).Reconcile\n\tgithub.com/couchbase/couchbase-operator/pkg/controller/controller.go:90\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

And it just hands on the same error over and over again. The bucket never ended up being created and the pods does not switch to the ready state.

If I set the number of couchbase server nodes to 1, it works, but if I keep it to 3 as it is the default in the helm chart, this fails.

I also tried the same config in a real cluster with 3 bare metal worker nodes in L3 connectivity, cilium as CNI, fails exactly with the same problem.

Cheers.
