### ISSUE TITLE
Couchbase cluster created is giving timeout on operation.

### ISSUE THREAD

**Issue by sbhardwaj-mt** [couchbase-partners/helm-charts#2]
Environment: Docker for Desktop with kubernetes.

The couchbase connection to the pod is successful, nslookup gives perfect result. but getting timeout when inserting any document in the bucket. (operation is timed out)  

couchbase-operator values.yaml
[values.yaml.txt](https://github.com/couchbase-partners/helm-charts/files/3098441/values.yaml.txt)

couchbase-cluster values.yaml
[values.yaml.txt](https://github.com/couchbase-partners/helm-charts/files/3098442/values.yaml.txt)

**Comment by tahmmee** [comment]
Hi Shriraj,

In the values.yaml for the cluster, you bucket named `globalcontext` is not being created.  What you need to do is override the name of default bucket with the following yaml instead
```
  buckets:
    default:
      # The type of bucket to use
      type: couchbase
      # The bucket name
      name: globalcontext
```
Also, how are you doing the doc insertion?  If you are using NodePort then your clients need to be Pods in the same network as the couchbase pods, otherwise you will need to use LoadBalancers.
