### ISSUE TITLE
default bucket always get created couchbaseBuckets.default: null not working

### ISSUE THREAD

**Issue by LordNoteworthy** [couchbase-partners/helm-charts#27]
Hey,

Helm version: 3.4.0
Couchbase operator: 2.0.2 

Settting `couchbaseBuckets.default: null` in the Helm values does not prevent the `default` bucket from being created.

Cheers.

**Comment by tahmmee** [comment]
Hey @LordNoteworthy 

Sorry, the comment there needs to be updated.
Override path is `buckets.default: null`
Also, if you are defining a different bucket, then it will use whatever you have set as `name` ie, the following defines an alternative bucket named `other`:
```yaml
  default: null
  other:
    # Kind of bucket
    kind: CouchbaseBucket
    # Name of the bucket
    name: other
```
Or if you omit `buckets.<id>.name` the map `<id>` will be used as bucket name
