### ISSUE TITLE
Helm installation fails with: cannot create resource pods/exec

### ISSUE THREAD

**Issue by LordNoteworthy** [couchbase-partners/helm-charts#37]
Hello,

Using couchbase operator v2.1.8

Helm installation fails in AWS (Kops deployment):

Operator log keep logging this error in a loop:
```
{"level":"error","ts":1613731797.4552727,"logger":"cluster","msg":"Reconciliation failed","cluster":"default/mars-couchbase-cluster","error":"remote command on mars-couchbase-cluster-0001 failed: pods \"mars-couchbase-cluster-0001\" is forbidden: User \"system:serviceaccount:default:mars-couchbase-operator\" cannot create resource \"pods/exec\" in API group \"\" in the namespace \"default\"","stacktrace":"github.com/couchbase/couchbase-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/couchbase/jenkins/workspace/couchbase-operator-build/goproj/src/github.com/couchbase/couchbase-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).runReconcile\n\t/home/couchbase/jenkins/workspace/couchbase-operator-build/goproj/src/github.com/couchbase/couchbase-operator/pkg/cluster/cluster.go:370\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).Update\n\t/home/couchbase/jenkins/workspace/couchbase-operator-build/goproj/src/github.com/couchbase/couchbase-operator/pkg/cluster/cluster.go:387\ngithub.com/couchbase/couchbase-operator/pkg/controller.(*CouchbaseClusterReconciler).Reconcile\n\t/home/couchbase/jenkins/workspace/couchbase-operator-build/goproj/src/github.com/couchbase/couchbase-operator/pkg/controller/controller.go:86\ngithub.com/couchbase/couchbase-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/couchbase/jenkins/workspace/couchbase-operator-build/goproj/src/github.com/couchbase/couchbase-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/couchbase/couchbase-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/couchbase/jenkins/workspace/couchbase-operator-build/goproj/src/github.com/couchbase/couchbase-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/couchbase/couchbase-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/couchbase/jenkins/workspace/couchbase-operator-build/goproj/src/github.com/couchbase/couchbase-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/couchbase/couchbase-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/couchbase/jenkins/workspace/couchbase-operator-build/goproj/src/github.com/couchbase/couchbase-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/couchbase/couchbase-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/couchbase/jenkins/workspace/couchbase-operator-build/goproj/src/github.com/couchbase/couchbase-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
❯ kl mars-couchbase-operator-848658bb94-vw
```

- Pods output:
```
kgp | grep couchbase
mars-couchbase-admission-controller-55fcc5df77-pm6xr   1/1     Running    0          34m
mars-couchbase-cluster-0000                            0/1     Running    0          33m
mars-couchbase-cluster-0001                            0/1     Running    0          32m
mars-couchbase-cluster-0002                            0/1     Running    0          32m
mars-couchbase-operator-848658bb94-vwngf               1/1     Running    0          34m
```

- Pod ouput:
```
❯ kl mars-couchbase-cluster-0000 -f
Starting Couchbase Server -- Web UI available at http://<ip>:8091
and logs available in /opt/couchbase/var/lib/couchbase/logs
chown: changing ownership of 'var/lib/couchbase': Operation not permitted
```

Cheers.

**Comment by tahmmee** [comment]
Hi @LordNoteworthy this looks like a permissions issue with container filesystem. Is the cluster running with persistent volumes?
If so, it could be that the fsGroup needs to be provided to specify the group id which is allowed to write to the volume:
https://docs.couchbase.com/operator/current/concept-persistent-volumes.html#using-storage-classes
(although this tends to be more of an openshift issue).

**Comment by LordNoteworthy** [comment]
Thanks @tahmmee 

Yes I am using persistent volumes.

Here is my config:
```yaml
        volumeMounts:
          default: couchbase
          data: couchbase
          index: couchbase
        # ServerGroups define the set of availability zones we want to distribute pods over.
        serverGroups: []
        # Pod defines the policy to create pod for the couchbase pod.
        pod:
          spec:
            containers:
    # VolumeClaimTemplates define the desired characteristics of a volume
    # that can be requested and claimed by a pod.
    volumeClaimTemplates:
    - metadata:
        name: couchbase
      spec:
        storageClassName: default
        resources:
          requests:
            storage: 60Gi
```

On AWS, the default storage class for me is ebs.
