### ISSUE TITLE
Create multiple buckets at the container creation time.

### ISSUE THREAD

**Issue by hoongeun** [couchbase-partners/helm-charts#45]
A single bucket declaration does work
```yaml
buckets:
  default:
    name: AA
```

But, when I declare multiple buckets in `values.yaml`, it didn't apply properly.
These are my codes.

```yaml
buckets:
  aa:
    kind: CouchbaseBucket
    resourceName: aa
    name: AA
    memoryQuota: 64Mi
    replicas: 1
    ioPriority: high
    evictionPolicy: fullEviction
    conflictResolution: seqno
    enableFlush: true
    enableIndexReplica: false
    compressionMode: "passive"
  bb:
    kind: CouchbaseBucket
    resourceName: bb
    name: BB
    memoryQuota: 64Mi
    replicas: 1
    ioPriority: high
    evictionPolicy: fullEviction
    conflictResolution: seqno
    enableFlush: true
    enableIndexReplica: false
    compressionMode: "passive"
```

```yaml
buckets:
  default:
    - kind: CouchbaseBucket
      resourceName: aa
      name: AA
      memoryQuota: 64Mi
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: "passive"
    - kind: CouchbaseBucket
      resourceName: bb
      name: BB
      memoryQuota: 64Mi
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: "passive"
```

And adding bucket in web console also doesn't work.
Is there any ways to create multiple buckets in creation time?

**Comment by tahmmee** [comment]
The yaml from the 1st snippet is correct here and I checked that the buckets are being created without any problems:
```bash
kubctl get couchbasebuckets
NAME   MEMORY QUOTA   REPLICAS   IO PRIORITY   EVICTION POLICY   CONFLICT RESOLUTION   AGE
aa     64Mi           1          high          fullEviction      seqno                 3s
bb     64Mi           1          high          fullEviction      seqno                 3s
```

Note you want to include default bucket as `null` if you do not want that included.
```yaml
buckets:
  default: null
  aa: 
    kind: CouchbaseBucket
    resourceName: aa
    ...
  bb:
    kind: CouchbaseBucket
    resourceName: bb 
    ...
```
