### ISSUE TITLE
helm installation tls.generate.true

### ISSUE THREAD

**Issue by allanian** [couchbase-partners/helm-charts#52]
hello, can you help me with tls issue: **tlsMinVersion - Supported TLS versions**
``` 
{"level":"info","ts":1623863121.2887464,"logger":"cluster","msg":"Reconciliation failed","cluster":"couchbase/apicbdev-couchbase-cluster","error":"unexpected status code: request failed POST https://apicbdev-couchbase-cluster-0002.apicbdev-couchbase-cluster.couchbase.svc:18091/settings/security 400 Bad Request: {\"errors\":[\"tlsMinVersion - Supported TLS versions are tlsv1.2, tlsv1.1, tlsv1\"]}","stack":"github.com/couchbase/couchbase-operator/pkg/util/couchbaseutil.Client.doRequest\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/util/couchbaseutil/core.go:267\ngithub.com/couchbase/couchbase-operator/pkg/util/couchbaseutil.(*Client).Post\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/util/couchbaseutil/core.go:315\ngithub.com/couchbase/couchbase-operator/pkg/util/couchbaseutil.(*Request).On.func1\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/util/couchbaseutil/api.go:214\ngithub.com/couchbase/couchbase-operator/pkg/util/couchbaseutil.(*Request).On\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/util/couchbaseutil/api.go:241\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).updateSecuritySettings\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/cluster/tls.go:1022\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).reconcileTLSPostTopologyChange\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/cluster/tls.go:1107\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).reconcile\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/cluster/reconcile.go:192\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).runReconcile\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/cluster/cluster.go:506\ngithub.com/couchbase/couchbase-operator/pkg/cluster.(*Cluster).Update\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/cluster/cluster.go:549\ngithub.com/couchbase/couchbase-operator/pkg/controller.(*CouchbaseClusterReconciler).Reconcile\n\t/home/couchbase/jenkins/workspace/couchbase-k8s-microservice-build/couchbase-operator/pkg/controller/controller.go:90\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/couchbase/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/couchbase/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/couchbase/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/couchbase/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/couchbase/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/couchbase/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/couchbase/go/pkg/mod/k8s.io/apimachinery@v0.19.4/pkg/util/wait/wait.go:90"}
{"level":"info","ts":1623863121.2981336,"logger":"cluster","msg":"Resource updated","cluster":"couchbase/apicbdev-couchbase-cluster","diff":"  (\n  \t\"\"\"\n  \t... // 26 identical lines\n  \t  status: \"True\"\n  \t  type: Scaling\n+ \t- lastTransitionTime: \"2021-06-16T17:05:21Z\"\n+ \t  lastUpdateTime: \"2021-06-16T17:05:21Z\"\n+ \t  message: 'unexpected status code: request failed POST https://apicbdev-couchbase-cluster-0002.apicbdev-couchbase-cluster.couchbase.svc:18091/settings/security 400 Bad Request: {\"errors\":[\"tlsMinVersion - Supported TLS versions are tlsv1.2, tlsv1.1, tlsv1\"]}'\n+ \t  reason: ErrorEncountered\n+ \t  status: \"True\"\n+ \t  type: Error\n  \tcurrentVersion: 6.6.2\n  \tmembers:\n  \t... // 6 identical lines\n  \t\"\"\"\n  )\n"}
{"level":"info","ts":1623863121.3221796,"logger":"cluster","msg":"unable to update status","cluster":"couchbase/apicbdev-couchbase-cluster","error":"CouchbaseCluster.couchbase.com \"apicbdev-couchbase-cluster\" is invalid: status.conditions.type: Unsupported value: \"Error\": supported values: \"Available\", \"Balanced\", \"ManageConfig\", \"Scaling\", \"Upgrading\", \"Hibernating\""}
{"level":"info","ts":1623863121.3378112,"logger":"cluster","msg":"Resource updated","cluster":"couchbase/apicbdev-couchbase-cluster","diff":"  (\n  \t\"\"\"\n  \t... // 26 identical lines\n  \t  status: \"True\"\n  \t  type: Scaling\n+ \t- lastTransitionTime: \"2021-06-16T17:05:21Z\"\n+ \t  lastUpdateTime: \"2021-06-16T17:05:21Z\"\n+ \t  message: 'unexpected status code: request failed POST https://apicbdev-couchbase-cluster-0002.apicbdev-couchbase-cluster.couchbase.svc:18091/settings/security 400 Bad Request: {\"errors\":[\"tlsMinVersion - Supported TLS versions are tlsv1.2, tlsv1.1, tlsv1\"]}'\n+ \t  reason: ErrorEncountered\n+ \t  status: \"True\"\n+ \t  type: Error\n  \tcurrentVersion: 6.6.2\n  \tmembers:\n  \t... // 6 identical lines\n  \t\"\"\"\n  )\n"}

````
## it's my values.yaml
```
helm upgrade --install apicbdev -n couchbase --values values_dev.yaml couchbase/couchbase-operator
```
```

install:
  couchbaseOperator: true
  admissionController: true
  couchbaseCluster: true
  syncGateway: false

couchbaseOperator:
  name: "couchbase-operator"
  image:
    repository: couchbase/operator
    tag: 2.2.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  commandArgs:
    pod-create-timeout: 10m
  resources: {}
  nodeSelector: {}
  tolerations: []

admissionController:
  name: "couchbase-admission-controller"
  image:
    repository: couchbase/admission-controller
    tag: 2.2.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  commandArgs:
    validate-secrets: true
    validate-storage-classes: true
    default-file-system-group: true
  resources: {}
  nodeSelector: {}
  tolerations: []
  verboseLogging: false
  runAsNonRoot: true

admissionService:
  name:
  port: 443
  targetPort: 8443

admissionCA:
  cert:
  key:
  expiration: 365

admissionSecret:
  name:
  cert:
  key:

coredns:
  service:
  searches:
  - apicbdev-couchbase-cluster.couchbase.svc.cluster.local
  - couchbase.svc.cluster.local
  - svc.cluster.local
  - cluster.local

backups: {}
backuprestores: {}

users:
  user-management:
    password: gUWa%P4Gly4
    authSecret:
    authDomain: local
    roles:
      - name: query_update
        bucket: services
      - name: query_select
        bucket: services
      - name: query_insert
        bucket: services
      - name: query_delete
        bucket: services

# TLS Certs that will be used to encrypt traffic between operator and couchbase
tls:
  generate: true
  expiration: 365
  nodeToNodeEncryption:

buckets:
  default:
    # compress off,passive,active
    compressionMode: passive
    # how resolve concurrent write conflicts
    conflictResolution: seqno
    # -- EnableFlush defines whether a client can delete all documents in a bucket.
    enableFlush: false
    # -- EnableIndexReplica defines whether indexes for this bucket are
    # replicated. This field defaults to false.
    enableIndexReplica: true
    # -- EvictionPolicy controls how Couchbase handles memory exhaustion.
    evictionPolicy: fullEviction
    # -- IOPriority controls how many threads a bucket has, per pod, to process reads and writes.
    ioPriority: low
    # -- The type of the bucket to create by default.
    kind: CouchbaseBucket
    # -- MemoryQuota is a memory limit to the size of a bucket. 
    memoryQuota: 128Mi
    # -- Replicas defines how many copies of documents Couchbase server maintains.
    replicas: 1
  services:
    kind: CouchbaseBucket
    compressionMode: passive
    conflictResolution: seqno
    enableFlush: false
    enableIndexReplica: true
    evictionPolicy: fullEviction
    ioPriority: high
    memoryQuota: 200Mi
    replicas: 2
 


cluster:
  antiAffinity: true
  autoResourceAllocation:
    cpuLimits: '4'
    cpuRequests: '2'
    enabled: false
    overheadPercent: 25
  autoscaleStabilizationPeriod:
  backup:
    image: couchbase/operator-backup:1.1.0
    managed: true
  buckets:
    managed: true
  cluster:
    analyticsServiceMemoryQuota: 1Gi
    autoCompaction:
      databaseFragmentationThreshold:
        percent: 30
      parallelCompaction: false
      timeWindow:
        abortCompactionOutsideWindow: false
      tombstonePurgeInterval: 72h
      viewFragmentationThreshold:
        percent: 30
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: false
    autoFailoverOnDataDiskIssuesTimePeriod: 120s
    autoFailoverServerGroup: false
    autoFailoverTimeout: 120s
    # Quota for buckets
    dataServiceMemoryQuota: 6Gi
    eventingServiceMemoryQuota: 1Gi
    indexServiceMemoryQuota: 1Gi
    indexStorageSetting: memory_optimized
    indexer:
      logLevel: info
      maxRollbackPoints: 2
      memorySnapshotInterval: 200ms
      stableSnapshotInterval: 5s
      storageMode: memory_optimized
    query:
      backfillEnabled: true
      temporarySpace: 5Gi
      temporarySpaceUnlimited: false
    searchServiceMemoryQuota: 1Gi
  tls:
  enableOnlineVolumeExpansion: false
  enablePreviewScaling: false
  hibernate: false
  image: couchbase/server:6.6.2
  logging:
    audit:
      enabled: false
      garbageCollection:
        sidecar:
          age: 1h
          enabled: false
          image: busybox:1.32.1
          interval: 20m
      rotation:
        interval: 15m
        size: 20Mi
    server:
      configurationName: fluent-bit-config
      enabled: false
      manageConfiguration: true
      sidecar:
        configurationMountPath: /fluent-bit/config/
        image: couchbase/fluent-bit:1.0.1
  monitoring:
    prometheus:
      enabled: false
  name: 
  networking:
    adminConsoleServiceTemplate:
      spec:
        publishNotReadyAddresses: false
        type: LoadBalancer
    adminConsoleServices:
    - data
    disableUIOverHTTP: true
    disableUIOverHTTPS: false
    dns:
      domain: test.com
    exposeAdminConsole: true
    exposedFeatureServiceTemplate:
      spec:
        publishNotReadyAddresses: false
        type: LoadBalancer 
    exposedFeatures:
    - admin
    - client
    - xdcr
  paused: false
  platform: aws
  security:
    adminSecret: ''
    password: 'Qqweqweqw123123qe'
    rbac:
      managed: true
    username: Administrator
    fsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    sysctls: []
  servers:
    default:
      autoscaleEnabled: false
      env: []
      envFrom: []
      pod:
        volumeMounts:
          default: couchbase
          data:  couchbase
      services:
      - data
      - index
      - query
      - search
      - analytics
      - eventing
      size: 3
    volumeClaimTemplates:
    - metadata:
        name: couchbase
      spec:
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 15Gi
  softwareUpdateNotifications: false
  xdcr:
    managed: false


```
