### ISSUE TITLE
Error: `couchbase-operator.serviceAccountName` template not defined

### ISSUE THREAD

**Issue by jvelasquezjs** [couchbase-partners/helm-charts#6]
## Issue

Followed the installation instructions and had this issue:

```
Error: template: couchbase-operator/templates/couchbase-service-account.yaml:6:20: executing "couchbase-operator/templates/couchbase-service-account.yaml" at <{{template "couchbase-operator.serviceAccountName" .}}>: template "couchbase-operator.serviceAccountName" not defined
```

There is no definition of `couchbase-operator.serviceAccountName` in the `_helpers.tpl` file. Can this please be looked at? 

## Version

```
cat Chart.yaml
apiVersion: v2
appVersion: 2.0.0
description: A Helm chart to deploy the Couchbase Autonomous Operator for easily deploying,
  managing, and maintaining Couchbase Clusters. Couchbase Server is a NoSQL document
  database with a distributed architecture for performance, scalability, and availability.
  It enables developers to build applications easier and faster by leveraging the
  power of SQL with the flexibility of JSON.
home: https://couchbase.com
icon: https://couchbase-partners.github.io/helm-charts/assets/img/CB_Logomark_220.png
keywords:
- couchbase
- operator
- database
- nosql
- cluster
- replication
maintainers:
- email: kubernetes@couchbase.com
  name: Couchbase Cloud Native Team
- email: tommie@couchbase.com
  name: Tommie McAfee
name: couchbase-operator
sources:
- https://docs.couchbase.com/operator/current/helm-setup-guide.html
type: application
version: 2.0.0
```
